#!/bin/csh -f
# Το υποπρόγραμμα δεχεται τις σημαίες και το αρχείο στο οποίο θα ενεργήσει από
# τη διαδικασία run. Οι σημαίες βρίσκονται αποθηκευμένες στην μεταβλητή
# RUN_FLAGS και το αρχείο δίνεται ως το (μοναδικό) όρισμα της διαδικασίας argv[1].

set sourcefile = $argv[1]
set executablefile = $sourcefile:r
set objectfile = $executablefile.o
set projectfile = $executablefile.pro

if ( `echo $RUN_FLAGS | grep -c -e "-b"` == 1 ) then
    set boost
    set boostLink = "-lboost_atomic -lboost_chrono -lboost_container -lboost_context -lboost_coroutine -lboost_date_time -lboost_exception -lboost_filesystem -lboost_graph -lboost_iostreams -lboost_locale -lboost_log -lboost_log_setup -lboost_math_c99 -lboost_math_c99f -lboost_math_c99l -lboost_math_tr1 -lboost_math_tr1f -lboost_math_tr1l -lboost_prg_exec_monitor -lboost_program_options -lboost_python -lboost_random -lboost_regex -lboost_serialization -lboost_signals -lboost_stacktrace_addr2line -lboost_stacktrace_backtrace -lboost_stacktrace_basic -lboost_stacktrace_noop -lboost_system -lboost_test_exec_monitor -lboost_thread -lboost_timer -lboost_type_erasure -lboost_unit_test_framework -lboost_wave -lboost_wserialization"
endif

if ( `echo $RUN_FLAGS | grep -c -e "-q"` == 1 ) set qt

# Έλεγχος αν δόθηκαν σημαίες.
if ( `echo $RUN_FLAGS | grep -c -e "-q"` == 1 ) then				# Πρόγραμμα Qt

		qmake -project -norecursive -o $projectfile
		mv $projectfile $executablefile.pro_old
		sed -f ~/sed_scripts/qt $executablefile.pro_old > $projectfile
		rm *.pro_old
		if ( `echo $RUN_FLAGS | grep -c -e "-p"` != 1 ) then
			qmake $projectfile
			make
			./$executablefile
			if ( `echo $RUN_FLAGS | grep -c -e "-k"` != 1 )	rm Makefile $executablefile *.pro *.o ???_*.cpp
		endif

else

    if ( $?boost ) then

    	if ( `echo $RUN_FLAGS | grep -c -e "-c"` == 1 ) then
	    	g++ -c -std=c++14 -pthread -o $objectfile $sourcefile $boostLink
	    else
		    g++ -std=c++14 -pthread -o $executablefile $sourcefile $boostLink
	    	clear
		    ./$executablefile
		    if ( `echo $RUN_FLAGS | grep -c -e "-k"` != 1 ) rm $executablefile
    	endif

    else

        if ( `echo $RUN_FLAGS | grep -c -e "-c"` == 1 ) then
	    	g++ -c -std=c++14 -pthread -o $objectfile $sourcefile
	    else
		    g++ -std=c++14 -pthread -o $executablefile $sourcefile
	    	clear
		    ./$executablefile
		    if ( `echo $RUN_FLAGS | grep -c -e "-k"` != 1 ) rm $executablefile
    	endif

    endif

endif
