#!/bin/csh -f
# Το υποπρόγραμμα δεχεται τις σημαίες και το αρχείο στο οποίο θα ενεργήσει από
# τη διαδικασία run. Οι σημαίες βρίσκονται αποθηκευμένες στην μεταβλητή
# RUN_FLAGS και το αρχείο δίνεται ως το (μοναδικό) όρισμα της διαδικασίας argv[1].

set sourcefile = $argv[1]
set fileroot = $sourcefile:r
set dvifile = $sourcefile.dvi

if ( `echo $RUN_FLAGS | grep -c -e "-t"` == 1 ) then
	tex $sourcefile
else
	latex $sourcefile
	bibtex $fileroot
	latex $sourcefile
	latex $sourcefile
endif
dvips $fileroot.dvi
gv $fileroot.ps
if ( `echo $RUN_FLAGS | grep -c -e "-k"` != 1 ) rm *.log *.dvi
