#!/bin/csh -f
# Το υποπρόγραμμα δεχεται τις σημαίες και το αρχείο στο οποίο θα ενεργήσει από
# τη διαδικασία run. Οι σημαίες βρίσκονται αποθηκευμένες στην μεταβλητή
# RUN_FLAGS και το αρχείο δίνεται ως το (μοναδικό) όρισμα της διαδικασίας argv[1].

set sourcefile = $argv[1]
set fileext = $sourcefile:e

clear
if ( $fileext == "pl" ) then
	perl -w $sourcefile
else if ( $fileext == "py" ) then
	python3 $sourcefile
else
	csh $sourcefile
endif


